### ISSUE TITLE
assert (boxes1[:, 2:] >= boxes1[:, :2]).all()

### ISSUE THREAD

**Issue by cxq1** [IDEA-opensource/DN-DETR#33]
Traceback (most recent call last):
  File "main.py", line 427, in <module>
    main(args)
  File "main.py", line 355, in main
    args.clip_max_norm, wo_class_error=wo_class_error, lr_scheduler=lr_scheduler, args=args, logger=(logger if args.save_log else None))
  File "/home/cxq/dp_work/objectdetection/DN-DETR/engine.py", line 50, in train_one_epoch
    loss_dict = criterion(outputs, targets, mask_dict)
  File "/home/cxq/.conda/envs/torch10/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cxq/dp_work/objectdetection/DN-DETR/models/DN_DAB_DETR/DABDETR.py", line 371, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/home/cxq/.conda/envs/torch10/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cxq/.conda/envs/torch10/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/cxq/dp_work/objectdetection/DN-DETR/models/DN_DAB_DETR/matcher.py", line 83, in forward
    cost_giou = -generalized_box_iou(box_cxcywh_to_xyxy(out_bbox), box_cxcywh_to_xyxy(tgt_bbox))
  File "/home/cxq/dp_work/objectdetection/DN-DETR/util/box_ops.py", line 52, in generalized_box_iou
    assert (boxes1[:, 2:] >= boxes1[:, :2]).all()

I'm not sure why I reported this error during training, I've trained Epoch: [38] [12440/14785] eta: 0:17:40

**Comment by artest08** [comment]
I am also following these kind of errors in detr architectures in recent weeks. I do not come across in this repo but one of my architectural modification to dab-deformable detr leads to the same error. 

Are you directly trying to replicate the result of the repo or did you make some modifications. If there are some modifications, what are they? 

facebookresearch/detr#101

**Comment by FengLi-ust** [comment]
Hey, this means your modification to the code fails to make the model work and produces illegal box predictions. For example, here the mistake means the value of the bottom left point coordinates of the box is larger than the top right point.

**Comment by cxq1** [comment]
> 
It is strange that this problem occurs in the middle of the training, and the results of the previous training are ok

**Comment by cxq1** [comment]
> I am also following these kind of errors in detr architectures in recent weeks. I do not come across in this repo but one of my architectural modification to dab-deformable detr leads to the same error.
> 
> Are you directly trying to replicate the result of the repo or did you make some modifications. If there are some modifications, what are they?
> 
> [facebookresearch/detr#101](https://github.com/facebookresearch/detr/issues/101)

It is strange that this problem occurs in the middle of the training, and the results of the previous training are ok

**Comment by cxq1** [comment]
> 嘿，这意味着您对代码的修改无法使模型工作并产生非法的框预测。例如，这里的错误表示框的左下点坐标值大于右上点。

It is strange that this problem occurs in the middle of the training, and the results of the previous training are ok
