### ISSUE TITLE
 Sizes of tensors must match except in dimension 1. 

### ISSUE THREAD

**Issue by cxq1** [IDEA-opensource/DN-DETR#34]
Traceback (most recent call last):
  File "main.py", line 428, in <module>
    main(args)
  File "main.py", line 388, in main
    wo_class_error=wo_class_error, args=args, logger=(logger if args.save_log else None)
  File "/home/cxq/.conda/envs/torch10/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/cxq/dp_work/objectdetection/DN-DETR/engine.py", line 221, in evaluate
    res_info = torch.cat((_res_bbox, _res_prob.unsqueeze(-1), _res_label.unsqueeze(-1)), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 900 but got size 300 for tensor number 1 in the list

This problem occurs when the code is tested after it has been trained

**Comment by FengLi-ust** [comment]
It seems you set the wrong dimension. Please check your code.

**Comment by cxq1** [comment]
> It seems you set the wrong dimension. Please check your code.

I didn't change the code, I ran the code with --use_dn --amp --save_results
The code works fine if -- save_results is not used

**Comment by FengLi-ust** [comment]
This parameter is directly inherited from DAB-DETR and we do not verify it.
