### ISSUE TITLE
use pretrain model error

### ISSUE THREAD

**Issue by myseverus** [IDEA-opensource/DN-DETR#37]
Hi！I'm in trouble
I train my own datase with pre-trained models
--pretrain_model_path checkpoint.pth
the result error:
Traceback (most recent call last):
  File "C:/Users/20825/Desktop/detr_code/DN-DETR-main/main.py", line 426, in <module>
    main(args)
  File "C:/Users/20825/Desktop/detr_code/DN-DETR-main/main.py", line 352, in main
    train_stats = train_one_epoch(
  File "C:\Users\20825\Desktop\detr_code\DN-DETR-main\engine.py", line 52, in train_one_epoch
    outputs = model(samples)
  File "C:\anaconda\envs\Detr\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\20825\Desktop\detr_code\DN-DETR-main\models\DN_DAB_DETR\DABDETR.py", line 176, in forward
    prepare_for_dn(dn_args, embedweight, src.size(0), self.training, self.num_queries, self.num_classes,
  File "C:\Users\20825\Desktop\detr_code\DN-DETR-main\models\DN_DAB_DETR\dn_components.py", line 61, in prepare_for_dn
    targets, scalar, label_noise_scale, box_noise_scale, num_patterns = dn_args
TypeError: cannot unpack non-iterable NoneType object

Thank you for your answer

**Comment by myseverus** [comment]
sorry,I found the reason

**Comment by jiaowanger** [comment]
What's the reason? How can I fix it

**Comment by zi-boop** [comment]
What's the reason? How can I fix it

**Comment by Srivatsa1648** [comment]
if i train without check points i am getting very less ap and if use checkpoints i facing an error pls reply if you have solved the issue
